# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DummyChat' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DummyChat
  source 'https://github.com/CocoaPods/Specs.git'
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'

  pod 'Starscream', '~> 1.1.3'
  pod 'Alamofire', '~> 3.4'
end
